### ISSUE TITLE
Signalling through Peers

### ISSUE THREAD

**Issue by daviddias** [daviddias/webrtc-explorer#12]
Use the P2P Overlay to exchange the signalling data (avoid needing the Signalling Server)

**Comment by jimmywarting** [comment]
Is the project dead?

[simple-peer-chord](https://github.com/oxyflour/simple-peer-chord) and [peer-relay](https://github.com/xuset/peer-relay/) seems to have figure it out

**Comment by daviddias** [comment]
Not "dead", it has served its purpose, results at:

- https://github.com/daviddias/thesis.browserCloud.js/blob/master/document.pdf
- http://daviddias.me/blog/enter-webrtc-explorer/
- http://daviddias.me/blog/webrtc-ring/

https://github.com/oxyflour/simple-peer-chord looks super rad! Thanks for sharing
