### ISSUE TITLE
RFC - Where to go next

### ISSUE THREAD

**Issue by daviddias** [daviddias/webrtc-explorer#5]
There are a collection of things that I have in the top of my mind that could be done next, in order to make the project more interesting and useful for more people. I'm sure there might be a lot of use cases I still don't know yet, if you have one or anything you would like webrtc-explorer to do, please go ahead and share :)
- [ ] Hybrid nodes - make webrtc-explorer both work on the browser and in node
- [ ] Improve performance
  - Put RTCPeerConnections inside WebWorkers (when the WebRTC API is available inside a WebWorker)
- [ ] Decentralised signalling - Enable to do signalling through the DHT, instead of using always the signalling server
- [ ] Self healing - let the peers restore DHT state, if the signalling server goes down 

Other ideas:
- Right now routing works in a `Store and Forward mode` (like IP or DNS recursive mode), but it can be interesting to see if an iterative mode (like bittorrent or DNS iterative mode) could be also be practical and offer any benefit

**Comment by iaaaan** [comment]
I don't know if there are priorities coming with this list, but decentralized signalling is incredibly exciting :)

Among the many use cases, I'm especially interested about the potential for truly independant and very large scale distributed data storage (decentralizing facebook posts, anyone?)

**Comment by diasdavid** [comment]
@iaaaan thank you for your comment :) I've been working more focused recently on https://ipfs.io/ which I believe it is the solution you are looking for your case, let mw know what you think! :)

**Comment by iaaaan** [comment]
I am mind blown. IPFS seems to be the solution I've been looking for for a while. Thanks @diasdavid, keep up the great work (:

**Comment by triangle42** [comment]
Decentralised signalling would be great!

**Comment by xj9** [comment]
I am very interesting in seeing a working DHT in the browser. Its definitely something that I would want to make heavy use of.

**Comment by diasdavid** [comment]
@xj9 it works, you can check a demo here http://blog.daviddias.me/2015/03/22/enter-webrtc-explorer :):)
